### ISSUE TITLE
Error: could not get network stats

### ISSUE THREAD

**Issue by nepeta-cataria** [microsoft/ethr#95] opened 2019-08-31 21:33 UTC
Hello. 
The latest version built from f0074aeb3580492e611afed2c220db54f0d116a3 shows errors when launched as server:
`could not get network stats`
And also statistics section is empty when launched in UI mode.
Tested on Ubuntu 18.04

**Comment by scrollins** [comment] 2019-09-11 13:03
@nepeta-cataria are you saying you are seeing "could not get network stats"? when running a client test. I see the same error message when I have the server(`ethr -s -6`) running in a docker container and then try to run the ethr client in another docker container using the command `ethr -c server1 -m x -t b -n 10 -l 32KB -o bandwidth.txt`

**Comment by boyan-soubachov** [comment] 2019-09-13 17:37
Will have a look

**Comment by boyan-soubachov** [comment] 2019-09-13 17:50
My mistake, apologies. Will try and figure out a way of testing this in our TravisCI build.

@pgmsft , fix: https://github.com/microsoft/ethr/pull/96/files

**Comment by boyan-soubachov** [comment] 2019-09-15 17:15
@pgmsft : Amended fix (tested locally). https://github.com/microsoft/ethr/pull/97

**Comment by scrollins** [comment] 2019-09-16 15:03
Still seeing an issue. @boyan-soubachov ```root@occam-gateway-01:~# docker logs ethr
Listening on 9999 for TCP bandwidth tests
Listening on 9998 for TCP conn/s tests
Listening on 9996 for TCP latency tests
Listening on 9899 for HTTP bandwidth tests
Listening on 9799 for HTTPS bandwidth tests
Listening on 9896 for HTTP latency tests
Listening on 8888 for control plane
could not get network stats```

Steps to reproduce 
1. In root GH dir, ```docker build -t ethr:latest .  ```
2. docker-compose up(docker compose below)
```version: '3.7'

services:

  ethr_server:
    image: ethr:latest
    container_name: ethr
    network_mode: host
    command: "ethr -s -6"
```

Docker versions are as follows
```root@occam-gateway-01:~# docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:21:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:19:41 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
OS Version
```
root@occam-gateway-01:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

1.

**Comment by boyan-soubachov** [comment] 2019-09-18 11:50
Thank you @scrollins , I will have a look as soon as possible

**Comment by boyan-soubachov** [comment] 2019-09-22 08:24
@scrollins, mind pasting your output of `cat /proc/net/snmp` and `cat /proc/net/dev`?

**Comment by scrollins** [comment] 2019-09-23 13:20
This is my output as requested 
```root@occam-gateway-01:/app# cat /proc/net/snmp
Ip: Forwarding DefaultTTL InReceives InHdrErrors InAddrErrors ForwDatagrams InUnknownProtos InDiscards InDelivers OutRequests OutDiscards OutNoRoutes ReasmTimeout ReasmReqds ReasmOKs ReasmFails FragOKs FragFails FragCreates
Ip: 1 64 10538200 0 0 0 3 0 10535436 5804652 0 0 0 0 0 0 0 0 0
Icmp: InMsgs InErrors InCsumErrors InDestUnreachs InTimeExcds InParmProbs InSrcQuenchs InRedirects InEchos InEchoReps InTimestamps InTimestampReps InAddrMasks InAddrMaskReps OutMsgs OutErrors OutDestUnreachs OutTimeExcds OutParmProbs OutSrcQuenchs OutRedirects OutEchos OutEchoReps OutTimestamps OutTimestampReps OutAddrMasks OutAddrMaskReps
Icmp: 57 23 0 21 28 0 0 0 4 0 1 0 3 0 110 0 105 0 0 0 0 0 4 0 1 0 0
IcmpMsg: InType3 InType8 InType11 InType13 InType17 OutType0 OutType3 OutType14
IcmpMsg: 21 4 28 1 3 4 105 1
Tcp: RtoAlgorithm RtoMin RtoMax MaxConn ActiveOpens PassiveOpens AttemptFails EstabResets CurrEstab InSegs OutSegs RetransSegs InErrs OutRsts InCsumErrors
Tcp: 1 200 120000 -1 115289 13163 3904267 33220 1 12878542 17148402 172160 0 54007 0
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
Udp: 69228 149 0 69558 0 0 0 753215
UdpLite: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors IgnoredMulti
UdpLite: 0 0 0 0 0 0 0 0
root@occam-gateway-01:/app# cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eno1: 11847961119 18785830    0   68    0     0          0   2792191 1725081551 6823567    0    0    0     0       0          0
docker0:       0       0    0    0    0     0          0         0    11180      98    0    0    0     0       0          0
    lo: 19639111288  823694    0    0    0     0          0         0 19639111288  823694    0    0    0     0       0          0
  eno2:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eno3:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eno4:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eno5: 37911590883 30529216    0   61    0     0          0   3519282 12543507429 10267678    0    0    0     0       0          0```

**Comment by boyan-soubachov** [comment] 2019-09-29 18:39
@scrollins. I've had a look. Please note that according to the README.md file, we only use the Docker container to *build* the binary of interest (linux/windows/mac). 

As such _running_ `ethr` inside a docker container is currently unsupported. It also doesn't make much sense due to the added abstraction of the VM and could cause some measurement inaccuracies; even more so if the hypervisor you're running the container on moves the ethr process between logical processors.

Please let me know if you have any questions or if you want me to explain further. Overall I would recommend running ethr outside of containers.

**Comment by scrollins** [comment] 2019-10-01 13:29
Noted. Since there was a docker file, I figured it was supported to run it inside of a container. I am now running the ethr server on Ubuntu 18.04 and I still see the same error message as initially reported. Let me know what output I need to provide you to troubleshoot. Thanks

**Comment by pgmsft** [comment] 2019-10-01 17:27
@boyan-soubachov Can you please take a look? I think this is due to the validation you added for parsing the net dev data.

We do support running in container as it is useful to measure performance of container itself.

**Comment by boyan-soubachov** [comment] 2019-10-01 17:48
Will have a look. Was just unaware as the readme specifies building it in a container rather than running.

**Comment by boyan-soubachov** [comment] 2019-10-01 18:27
@scrollins, I'm having trouble reproducing your issue.

The output of those 2 files you gave me would logically work with the code. I was also successfully able to bring up the docker-compose service: ```λ ~/go/src/github.com/microsoft/ethr/ bvs-#95-fix_net_stats_3* sudo docker-compose up
Creating ethr ... done
Attaching to ethr
ethr           | Listening on 9999 for TCP bandwidth tests
ethr           | Listening on 9998 for TCP conn/s tests
ethr           | Listening on 9996 for TCP latency tests
ethr           | Listening on 9899 for HTTP bandwidth tests
ethr           | Listening on 9799 for HTTPS bandwidth tests
ethr           | Listening on 9896 for HTTP latency tests
ethr           | Listening on 8888 for control plane
```

Could you please pull the latest commit of ethr and rebuild the docker image. It now has much better and more verbose error logging so we'll be able to see exactly where in the function the error occurs.

**Comment by scrollins** [comment] 2019-10-01 22:48
I pulled in your changes w/ the logging and rebuilt the binary. We aren't seeing the error anymore. Thanks for pushing up those changes!

**Comment by boyan-soubachov** [comment] 2019-10-07 17:12
@pgmsft, mind closing this issue?

**Closed** 2019-10-07 18:05 UTC
